Expose Brand & MPN to Woocommerce UI
facebook/facebook-for-woocommerce pull request #2842
Opened 2024-12-18 19:29 UTC by devbodaghe

Changes proposed in this Pull Request:

This PR introduces a new feature to the Facebook WooCommerce Plugin, allowing users to add a brand field to their products. With this update, we can seamlessly synchronize the brand field with the Facebook Commerce Manager platform.

<img width="989" alt="Screenshot 2024-10-30 at 18 08 06" src="https://github.com/user-attachments/assets/0efc54f9-88f1-487e-881b-300bd203a3dd">
<img width="527" alt="Screenshot 2024-10-30 at 18 08 36" src="https://github.com/user-attachments/assets/d0cf9ae0-293b-4685-a033-643dc6214a1f">

2025-01-10 14:54 UTC, mshymon commented
@devbodaghe, is the screenshot  in the description missing MPN field? 
Also, it is easier to compare the change if you include before / after screenshots and potentially highlight area with the new elements in red.  

Also, any particular reason why Brand goes between image URL and Price?

2025-01-10 15:07 UTC, mshymon requested changes

2025-01-10 15:07 UTC, mshymon commented on includes/fbproduct.php
> +		}
Why do we need to keep variable $this->fb_brand, why not always read it from the DB via get_post_meta() when we need the value? Maintaining an intermediate variable  in sync can lead to bugs.

2025-01-10 15:07 UTC, mshymon commented on includes/fbproduct.php
> +		return WC_Facebookcommerce_Utils::clean_string( $fb_brand );
If we call WC_Facebookcommerce_Utils::clean_string at the end, can we remove previous such calls in the code of this method?

2025-01-10 15:07 UTC, mshymon commented on includes/fbproduct.php
> +				if (is_array($attribute) && isset($attribute['key'])) {
Formatting, check also through the code

```suggestion
				if ( is_array( $attribute ) && isset( $attribute['key'] ) ) {
```

2025-01-10 19:00 UTC, devbodaghe commented
> @devbodaghe, is the screenshot in the description missing MPN field? Also, it is easier to compare the change if you include before / after screenshots and potentially highlight area with the new elements in red.
> 
> Also, any particular reason why Brand goes between image URL and Price?



> @devbodaghe, is the screenshot in the description missing MPN field? Also, it is easier to compare the change if you include before / after screenshots and potentially highlight area with the new elements in red.
> 
> Also, any particular reason why Brand goes between image URL and Price?

It's updated now

2025-01-10 19:06 UTC, devbodaghe commented on includes/fbproduct.php
> +		}
You make a good point and I have updated this without the need for this value.

2025-01-10 19:15 UTC, devbodaghe commented on includes/fbproduct.php
> +		return WC_Facebookcommerce_Utils::clean_string( $fb_brand );
Great point

2025-01-13 17:02 UTC, mshymon approved these changes

2025-01-13 17:02 UTC, mshymon commented on includes/fbproduct.php
> +				// Check if $attribute is an array and has the 'key' index
Comment is saying the same think as the code. Remove or add value why we do this check (not what we do)

2025-01-20 16:27 UTC, vinkmeta commented on bin/fb_google_category_to_attribute_mapping.json
It is not a good idea to modify this json as its a standard static file that is not supposed to be modified. The alternative approach is to filter Brand when surfacing GPC attributes so that it never get surfaced and you can introduce a new field called 'Brand' that will eventually use the existing brand field's values.

2025-01-20 22:23 UTC, devbodaghe commented on includes/Products/FBCategories.php
> +	private $keys_to_exclude = ['brand' => true];
Added associative array here to avoid lopping over regular array

2025-01-20 22:24 UTC, vinkmeta commented on includes/Products/FBCategories.php
> +		// error_log('fields_data' . print_r($fields_data, true));
Lets remove this error log

2025-01-20 22:25 UTC, vinkmeta commented on includes/fbproduct.php
> +
Lets remove this extra line

2025-01-21 02:40 UTC, vinkmeta commented
I manually tested this PR locally and discovered a critical bug: If a value for the Brand attribute is already saved and I then upgrade the plugin version, the Brand value appears empty. To fix this, you may need to fetch the Brand value while rendering this attribute in the Facebook.

2025-01-31 20:48 UTC, vinkmeta approved these changes

2025-02-06 09:11 UTC, closed without merging